
POST http://localhost/customer
Content-Type: application/json

{
  "email": "example@mail.ru",
  "phoneNumber": "899999999",
  "name": "Иван",
  "surname": "Иванов",
  "gender": "MALE",
  "birthdayDate": "2000-01-01",
  "addressDto": {
    "street": "Спартаковская",
    "house": 98,
    "apartment": "6А",
    "location": {
      "country": "Россия",
      "city": "Москва"
    }
  },
  "passwordHash": "1234qwer"
}

###
POST http://localhost/auth/login
Content-Type: application/x-www-form-urlencoded

email=example@mail.ru&password=1234qwer
###
#{
#  "accessToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQG1haWwucnUiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2F1dGgvbG9naW4iLCJleHAiOjE2ODgyOTM3ODV9.OC6rYjDwIDtrn9oZy9AaqnW9i-4_vIMJ2O9QLUPd07A",
#  "refreshToken": "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQG1haWwucnUiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2F1dGgvbG9naW4iLCJleHAiOjE2ODgzNzc3ODV9.HOb8cABBxqRjYL08iYsjNduRLJ2H4X0x5TWq06PDI54"
#}

###
GET http://localhost:80/customer
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJleGFtcGxlQG1haWwucnUiLCJyb2xlIjoiQ1VTVE9NRVIiLCJpc3MiOiJodHRwOi8vbG9jYWxob3N0L2F1dGgvbG9naW4iLCJleHAiOjE2ODgyOTM3ODV9.OC6rYjDwIDtrn9oZy9AaqnW9i-4_vIMJ2O9QLUPd07A

###

