name: auto

on:
  push:
    branches: [ "deploy" ]
  pull_request:
    branches: [ "deploy" ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 17 and Maven
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    - name: Test
      run: mvn test

  prepare-environment:
    runs-on: self-hosted
    needs: test
    steps:
      - name: docker-compose down
        run: docker-compose down || true
  deploy:
    runs-on: self-hosted
    needs: prepare-environment
    steps:
      - name: checkout repo
        uses: actions/checkout@v3
      - name: Set up Maven environment
        run: export MAVEN_OPTS="-Xmx4g -Xms1g"
      - name: Build with Maven
        run: mvn clean install -DskipTests
      - name: Build Docker Image
        run: docker build -t market_app_image .
      - name: Docker Compose Up
        run: docker-compose up

